# Nombre del microservicio
spring.application.name=api-gateway

# Puerto donde se ejecutará el Gateway
server.port=8090

# Dirección del servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Registrar la IP en Eureka
eureka.instance.prefer-ip-address=true

# ==========================
# RUTAS DEL GATEWAY
# ==========================

# Microservicio Venta
spring.cloud.gateway.mvc.routes[0].id=venta
spring.cloud.gateway.mvc.routes[0].uri=lb://VENTA
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/ventas/**

# Microservicio Cliente
spring.cloud.gateway.mvc.routes[1].id=cliente
spring.cloud.gateway.mvc.routes[1].uri=lb://CLIENTE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/clientes/**

# Microservicio Entrada
spring.cloud.gateway.mvc.routes[2].id=entrada
spring.cloud.gateway.mvc.routes[2].uri=lb://ENTRADA
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/entradas/**