spring.application.name=categoria

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/categoria
spring.datasource.username=root
spring.datasource.password=1234 //cambiar la contra por la que tenga mi BBDD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true