# ═══════════════════════════════════════════════════════════════
# VENTA — application-dev.yml (entorno local)
# ═══════════════════════════════════════════════════════════════

server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venta
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
